<a href="https://colab.research.google.com/github/vishwasvarma29/python_course/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
# 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
# 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
# 3D array
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [2]:
ones = np.ones((6,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [3]:
identity = np.eye(6)
print(identity)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [6]:
full_array = np.full((5,9),False)
print(full_array)

[[False False False False False False False False False]
 [False False False False False False False False False]
 [False False False False False False False False False]
 [False False False False False False False False False]
 [False False False False False False False False False]]


In [8]:
range_arr = np.arange(2, 101, 2)
print(range_arr)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [10]:
lin_space = np.linspace(1, 10, 5)
print(lin_space)

[ 1.    3.25  5.5   7.75 10.  ]


In [11]:
rand_int= np. random.randint(1, 10, (1, 30))
print(rand_int)

[[6 6 9 3 1 1 4 9 9 2 2 8 9 5 1 7 2 8 6 8 1 5 6 4 5 6 6 1 7 9]]


In [14]:
rand_float = np.random.rand(6,2)
print(rand_float)

[[0.6515369  0.43089822]
 [0.40273293 0.94681551]
 [0.81408051 0.00820652]
 [0.82130063 0.19876968]
 [0.86478671 0.65296157]
 [0.19705475 0.04804255]]


In [18]:
rand_norm = np.random.randn(4,5)
print(rand_norm)

[[-0.48019135 -0.15804749 -0.10749126  0.62921544  0.47567173]
 [-1.25944836  1.40250572  0.34306336  1.33324229  1.20316686]
 [-0.11864568  0.51695482 -0.60992703  0.72983864  0.34190701]
 [-0.76101779  2.30220081  0.93844273  0.7438408  -0.02789554]]


In [22]:
rand_choice=np.random.choice(['vishwas','goutham','nikhil','abhi'],6)
print(rand_choice)

['goutham' 'abhi' 'nikhil' 'vishwas' 'vishwas' 'abhi']


In [23]:
np.random.seed(42)
rand_arr=np.random.randint(6)
print(rand_arr)

3


In [33]:
arr=np.array([[1, 2], [4, 5],[6,7],[8,9]])
print(arr.shape)

(4, 2)


In [35]:
reshaped=arr.reshape(1,8)
print(reshaped)

[[1 2 4 5 6 7 8 9]]


In [36]:
flattened=arr.flatten()
print(flattened)

[1 2 4 5 6 7 8 9]


In [37]:
transposed=arr.T
print(transposed)

[[1 4 6 8]
 [2 5 7 9]]


In [38]:
arr=np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[:3])
print(arr[::2])


10
50
[20 30 40]
[10 20 30]
[10 30 50]


In [41]:
matrix=np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
print(matrix[1, 2])
print(matrix[0:3, 1])
print(matrix[0:2,0:2])

60
[20 50 80]
[[10 20]
 [40 50]]


In [45]:
arr=np.array([4,9,16,25,36])
print(arr+1)
print(arr*2)
print(arr**2)

[ 5 10 17 26 37]
[ 8 18 32 50 72]
[  16   81  256  625 1296]


In [46]:
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))

90
18.0
16.0


In [47]:
print(np.std(arr))
print(np.var(arr))

11.436782764396638
130.8


In [49]:
print(np.min(arr))
print(np.max(arr))

4
36


In [51]:
arr=np.array([4,9,16,25,36])
print(np.cumsum(arr))
print(np.cumprod(arr))

[ 4 13 29 54 90]
[     4     36    576  14400 518400]


In [53]:
arr=np.array([10, 20, 30, 40, 50])
bool_arr=arr % 2==0
print(bool_arr)

[ True  True  True  True  True]


In [57]:
filtered_arr=arr[arr>20]
print(filtered_arr)

[30 40 50]


In [58]:
arr=np.array([3, 1, 4, 1, 5, 9, 2, 6])
sorted_arr=np.sort(arr)
print(sorted_arr)

[1 1 2 3 4 5 6 9]


In [59]:
unique_vals=np.unique(arr)
print(unique_vals)

[1 2 3 4 5 6 9]


In [62]:
arr = np.array([10, 20, 30])
view_arr = arr.view()
view_arr[0] = 100
print(arr,view_arr)
# Deep copy
copy_arr = arr.copy()
copy_arr[0] = 200
print(copy_arr)

[100  20  30] [100  20  30]
[200  20  30]
